# -*- coding: utf-8 -*-
"""Assignment 1 HR Analytics (Employee Attrition)   : Classification with Machine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TMjCmsBm8zR11-4GChnQDbzZn0Qq3DRa
"""

# Assignment: Classification with Machine
# Learning Models
# Problem Statement
# The goal of this assignment is to apply multiple classification algorithms to real-world
# datasets. You will build, evaluate, and compare models such as Decision Tree, Random
# Forest, AdaBoost, XGBoost, and CatBoost.
# You are required to perform data exploration, preprocessing, model building, and
# optimization to understand how classification models behave on different datasets.
# Dataset Links
# 1. Telco Customer Churn – Kaggle
# 2. HR Analytics (Employee Attrition) – Kaggle
# 3. Stroke Prediction – Kaggle
# Assignment Guidelines
# 1. Data Understanding
# ●
# ●
# ●
# ●
# Load the dataset and display the first few rows.
# Identify the input features and the target variable.
# Check data types (numerical vs categorical).
# Check for missing values and duplicates.
# 2. Exploratory Data Analysis (EDA)
# ●
# Plot the distribution of the target variable.
# ●
# Visualize relationships between features and the target (e.g., Age vs Survival,
# MonthlyCharges vs Churn).
# ●
# Compare categories (e.g., Gender, Department, Smoking Status).
# ●
# Create a correlation heatmap for numerical features.
# 3. Data Preprocessing
# ●
# Encode categorical variables.
# ●
# Scale numerical features if required.
# ●
# Handle missing values appropriately.
# ●
# Split into training and testing sets.
# 4. Model Building (Apply All Classifiers)
# You must apply the following classifiers one by one:
# 1. Decision Tree
# 2. Random Forest
# 3. AdaBoost
# 4. XGBoost
# 5. CatBoost
# For each classifier:
# ●
# Train the model on training data.
# ●
# Evaluate on testing data using:
# ○
# Accuracy, Precision, Recall, F1-score
# ○
# Confusion Matrix
# 5. Model Optimization
# ●
# ●
# ●
# Perform hyperparameter tuning for at least 2 models (e.g., Random Forest &
# XGBoost).
# Compare tuned performance vs default.
# Discuss overfitting/underfitting observations.
# 6. Model Evaluation and Comparison
# ●
# ●
# ●
# Compare the performance of all 5 models in a summary table.
# Identify the best-performing model.
# Discuss which features are most important (Feature Importance plots for tree-based
# models).

!pip install catboost

import pandas as pd
import numpy as np
import joblib

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, recall_score, f1_score, r2_score
from sklearn.preprocessing import LabelEncoder

from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier

df = pd.read_csv("/content/WA_Fn-UseC_-HR-Employee-Attrition.csv")
df

df.info()

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

# Select only numeric columns
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns

# Apply MinMaxScaler
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

df

df['Attrition']

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Attrition'] = le.fit_transform(df['Attrition'])
df['Gender'] = le.fit_transform(df['Gender'])
df['MaritalStatus'] = le.fit_transform(df['MaritalStatus'])
df['Over18'] = le.fit_transform(df['Over18'])
df['OverTime'] = le.fit_transform(df['OverTime'])

df['BusinessTravel'].unique()

one_hot_encoding = pd.get_dummies(df['BusinessTravel'])
df = pd.concat([df, one_hot_encoding], axis=1)

df

target = df.groupby('Department')['Attrition'].mean()
df['Department'] = df['Department'].map(target)

target = df.groupby('EducationField')['Attrition'].mean()
df['EducationField'] = df['EducationField'].map(target)

target = df.groupby('JobRole')['Attrition'].mean()
df['JobRole'] = df['JobRole'].map(target)

df

df.info()

df.columns

x = df[['Age', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager', 'Non-Travel', 'Travel_Frequently',
       'Travel_Rarely']]
y = df['Attrition']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20)

# Model

models = {
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "AdaBoost": AdaBoostClassifier(),
    "XGBoost": XGBClassifier(use_label_encoder=False, eval_metric='logloss'),
    "CatBoost": CatBoostClassifier(verbose=0)  # suppress training output
}

# === Step 5: Train, Evaluate & Track Best Model ===
best_model = None
best_score = 0
best_name = ""

print("\n📊 Model Performance:\n")
for name, model in models.items():
    model.fit(x_train, y_train)
    preds = model.predict(x_test)

    acc = accuracy_score(y_test, preds)
    recall = recall_score(y_test, preds, average='weighted')
    f1 = f1_score(y_test, preds, average='weighted')
    r2 = r2_score(y_test, preds)

    print(f"{name}: Accuracy={acc:.4f}, Recall={recall:.4f}, F1={f1:.4f}, R²={r2:.4f}")

    if acc > best_score:
        best_score = acc
        best_model = model
        best_name = name

# === Step 6: Save Best Model ===
joblib.dump(best_model, f"{best_name}_best_model.pkl")
print(f"\n✅ Best model: '{best_name}' saved as '{best_name}_best_model.pkl' with Accuracy: {best_score:.4f}")

